# SSM Parameter Store Module - Main Configuration
# All application environment variables managed centrally

# ===================================
# Shared Parameters (used by multiple services)
# ===================================

resource "aws_ssm_parameter" "shared_aws_region" {
  name  = "/kishax/${var.environment}/shared/aws_region"
  type  = "String"
  value = var.aws_region
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_sqs_access_key_id" {
  name  = "/kishax/${var.environment}/shared/sqs_access_key_id"
  type  = "String"
  value = var.sqs_access_key_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_sqs_secret_access_key" {
  name  = "/kishax/${var.environment}/shared/sqs_secret_access_key"
  type  = "SecureString"
  value = var.sqs_secret_access_key
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_to_web_queue_url" {
  name  = "/kishax/${var.environment}/shared/to_web_queue_url"
  type  = "String"
  value = var.to_web_queue_url
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_to_mc_queue_url" {
  name  = "/kishax/${var.environment}/shared/to_mc_queue_url"
  type  = "String"
  value = var.to_mc_queue_url
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_to_discord_queue_url" {
  name  = "/kishax/${var.environment}/shared/to_discord_queue_url"
  type  = "String"
  value = var.to_discord_queue_url
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_mysql_host" {
  name  = "/kishax/${var.environment}/shared/mysql_host"
  type  = "String"
  value = var.mysql_host
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_mysql_database" {
  name  = "/kishax/${var.environment}/shared/mysql_database"
  type  = "String"
  value = var.mysql_database
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_mysql_user" {
  name  = "/kishax/${var.environment}/shared/mysql_user"
  type  = "String"
  value = var.mysql_user
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_mysql_password" {
  name  = "/kishax/${var.environment}/shared/mysql_password"
  type  = "SecureString"
  value = var.mysql_password
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_postgres_host" {
  name  = "/kishax/${var.environment}/shared/postgres_host"
  type  = "String"
  value = var.postgres_host
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_postgres_database" {
  name  = "/kishax/${var.environment}/shared/postgres_database"
  type  = "String"
  value = var.postgres_database
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_postgres_user" {
  name  = "/kishax/${var.environment}/shared/postgres_user"
  type  = "String"
  value = var.postgres_user
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_postgres_password" {
  name  = "/kishax/${var.environment}/shared/postgres_password"
  type  = "SecureString"
  value = var.postgres_password
  tags  = var.tags
}

resource "aws_ssm_parameter" "shared_auth_api_key" {
  name  = "/kishax/${var.environment}/shared/auth_api_key"
  type  = "SecureString"
  value = var.auth_api_key
  tags  = var.tags
}

# ===================================
# Dynamic Parameters (auto-generated by instances)
# ===================================

resource "aws_ssm_parameter" "dynamic_redis_mc_port" {
  name  = "/kishax/${var.environment}/dynamic/redis_mc_port"
  type  = "String"
  value = "6379"
  tags  = var.tags
}

resource "aws_ssm_parameter" "dynamic_redis_web_port" {
  name  = "/kishax/${var.environment}/dynamic/redis_web_port"
  type  = "String"
  value = "6380"
  tags  = var.tags
}

# Note: api_server_private_ip will be created/updated by user-data-api-server.sh
# We create a placeholder here to avoid errors
resource "aws_ssm_parameter" "dynamic_api_server_private_ip" {
  name  = "/kishax/${var.environment}/dynamic/api_server_private_ip"
  type  = "String"
  value = "0.0.0.0"  # Placeholder, will be updated by API server on boot

  lifecycle {
    ignore_changes = [value]  # Ignore changes made by EC2 user-data
  }

  tags = var.tags
}

# ===================================
# MC Server (i-a) Parameters
# ===================================

resource "aws_ssm_parameter" "mc_overall_memory" {
  name  = "/kishax/${var.environment}/mc/overall_memory"
  type  = "String"
  value = var.mc_overall_memory
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_seed_env" {
  name  = "/kishax/${var.environment}/mc/seed_env"
  type  = "String"
  value = var.mc_seed_env
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_confirm_base_url" {
  name  = "/kishax/${var.environment}/mc/mc_confirm_base_url"
  type  = "String"
  value = var.mc_confirm_base_url
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_redis_connection_timeout" {
  name  = "/kishax/${var.environment}/mc/redis_connection_timeout"
  type  = "String"
  value = var.mc_redis_connection_timeout
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_redis_command_timeout" {
  name  = "/kishax/${var.environment}/mc/redis_command_timeout"
  type  = "String"
  value = var.mc_redis_command_timeout
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_queue_mode" {
  name  = "/kishax/${var.environment}/mc/queue_mode"
  type  = "String"
  value = var.mc_queue_mode
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_sqs_worker_enabled" {
  name  = "/kishax/${var.environment}/mc/sqs_worker_enabled"
  type  = "String"
  value = var.mc_sqs_worker_enabled
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_sqs_worker_polling_interval_seconds" {
  name  = "/kishax/${var.environment}/mc/sqs_worker_polling_interval_seconds"
  type  = "String"
  value = var.mc_sqs_worker_polling_interval_seconds
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_sqs_worker_max_messages" {
  name  = "/kishax/${var.environment}/mc/sqs_worker_max_messages"
  type  = "String"
  value = var.mc_sqs_worker_max_messages
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_sqs_worker_wait_time_seconds" {
  name  = "/kishax/${var.environment}/mc/sqs_worker_wait_time_seconds"
  type  = "String"
  value = var.mc_sqs_worker_wait_time_seconds
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_sqs_worker_visibility_timeout_seconds" {
  name  = "/kishax/${var.environment}/mc/sqs_worker_visibility_timeout_seconds"
  type  = "String"
  value = var.mc_sqs_worker_visibility_timeout_seconds
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_log_level" {
  name  = "/kishax/${var.environment}/mc/log_level"
  type  = "String"
  value = var.mc_log_level
  tags  = var.tags
}

resource "aws_ssm_parameter" "mc_kishax_api_branch" {
  name  = "/kishax/${var.environment}/mc/kishax_api_branch"
  type  = "String"
  value = var.mc_kishax_api_branch
  tags  = var.tags
}

# ===================================
# Web Server (i-c) Parameters
# ===================================

resource "aws_ssm_parameter" "web_queue_mode" {
  name  = "/kishax/${var.environment}/web/queue_mode"
  type  = "String"
  value = var.web_queue_mode
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_sqs_worker_enabled" {
  name  = "/kishax/${var.environment}/web/sqs_worker_enabled"
  type  = "String"
  value = var.web_sqs_worker_enabled
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_nextauth_url" {
  name  = "/kishax/${var.environment}/web/nextauth_url"
  type  = "String"
  value = var.web_nextauth_url
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_nextauth_secret" {
  name  = "/kishax/${var.environment}/web/nextauth_secret"
  type  = "SecureString"
  value = var.web_nextauth_secret
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_google_client_id" {
  name  = "/kishax/${var.environment}/web/google_client_id"
  type  = "String"
  value = var.web_google_client_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_google_client_secret" {
  name  = "/kishax/${var.environment}/web/google_client_secret"
  type  = "SecureString"
  value = var.web_google_client_secret
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_discord_client_id" {
  name  = "/kishax/${var.environment}/web/discord_client_id"
  type  = "String"
  value = var.web_discord_client_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_discord_client_secret" {
  name  = "/kishax/${var.environment}/web/discord_client_secret"
  type  = "SecureString"
  value = var.web_discord_client_secret
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_twitter_client_id" {
  name  = "/kishax/${var.environment}/web/twitter_client_id"
  type  = "String"
  value = var.web_twitter_client_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_twitter_client_secret" {
  name  = "/kishax/${var.environment}/web/twitter_client_secret"
  type  = "SecureString"
  value = var.web_twitter_client_secret
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_email_host" {
  name  = "/kishax/${var.environment}/web/email_host"
  type  = "String"
  value = var.web_email_host
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_email_port" {
  name  = "/kishax/${var.environment}/web/email_port"
  type  = "String"
  value = var.web_email_port
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_email_user" {
  name  = "/kishax/${var.environment}/web/email_user"
  type  = "String"
  value = var.web_email_user
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_email_pass" {
  name  = "/kishax/${var.environment}/web/email_pass"
  type  = "SecureString"
  value = var.web_email_pass
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_email_from" {
  name  = "/kishax/${var.environment}/web/email_from"
  type  = "String"
  value = var.web_email_from
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_node_env" {
  name  = "/kishax/${var.environment}/web/node_env"
  type  = "String"
  value = var.web_node_env
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_port" {
  name  = "/kishax/${var.environment}/web/port"
  type  = "String"
  value = var.web_port
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_log_level" {
  name  = "/kishax/${var.environment}/web/log_level"
  type  = "String"
  value = var.web_log_level
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_internal_api_key" {
  name  = "/kishax/${var.environment}/web/internal_api_key"
  type  = "SecureString"
  value = var.web_internal_api_key
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_redis_connection_timeout" {
  name  = "/kishax/${var.environment}/web/redis_connection_timeout"
  type  = "String"
  value = var.web_redis_connection_timeout
  tags  = var.tags
}

resource "aws_ssm_parameter" "web_redis_command_timeout" {
  name  = "/kishax/${var.environment}/web/redis_command_timeout"
  type  = "String"
  value = var.web_redis_command_timeout
  tags  = var.tags
}

# ===================================
# API Server (i-b) Parameters
# ===================================

resource "aws_ssm_parameter" "api_redis_url_discord" {
  name  = "/kishax/${var.environment}/api/redis_url_discord"
  type  = "String"
  value = var.api_redis_url_discord
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_auth_api_enabled" {
  name  = "/kishax/${var.environment}/api/auth_api_enabled"
  type  = "String"
  value = var.api_auth_api_enabled
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_auth_api_port" {
  name  = "/kishax/${var.environment}/api/auth_api_port"
  type  = "String"
  value = var.api_auth_api_port
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_token" {
  name  = "/kishax/${var.environment}/api/discord_token"
  type  = "SecureString"
  value = var.api_discord_token
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_channel_id" {
  name  = "/kishax/${var.environment}/api/discord_channel_id"
  type  = "String"
  value = var.api_discord_channel_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_chat_channel_id" {
  name  = "/kishax/${var.environment}/api/discord_chat_channel_id"
  type  = "String"
  value = var.api_discord_chat_channel_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_admin_channel_id" {
  name  = "/kishax/${var.environment}/api/discord_admin_channel_id"
  type  = "String"
  value = var.api_discord_admin_channel_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_rule_channel_id" {
  name  = "/kishax/${var.environment}/api/discord_rule_channel_id"
  type  = "String"
  value = var.api_discord_rule_channel_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_rule_message_id" {
  name  = "/kishax/${var.environment}/api/discord_rule_message_id"
  type  = "String"
  value = var.api_discord_rule_message_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_guild_id" {
  name  = "/kishax/${var.environment}/api/discord_guild_id"
  type  = "String"
  value = var.api_discord_guild_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_discord_presence_activity" {
  name  = "/kishax/${var.environment}/api/discord_presence_activity"
  type  = "String"
  value = var.api_discord_presence_activity
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_be_default_emoji_name" {
  name  = "/kishax/${var.environment}/api/be_default_emoji_name"
  type  = "String"
  value = var.api_be_default_emoji_name
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_aws_sqs_max_messages" {
  name  = "/kishax/${var.environment}/api/aws_sqs_max_messages"
  type  = "String"
  value = var.api_aws_sqs_max_messages
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_aws_sqs_wait_time_seconds" {
  name  = "/kishax/${var.environment}/api/aws_sqs_wait_time_seconds"
  type  = "String"
  value = var.api_aws_sqs_wait_time_seconds
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_sqs_worker_polling_interval" {
  name  = "/kishax/${var.environment}/api/sqs_worker_polling_interval"
  type  = "String"
  value = var.api_sqs_worker_polling_interval
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_sqs_worker_max_messages" {
  name  = "/kishax/${var.environment}/api/sqs_worker_max_messages"
  type  = "String"
  value = var.api_sqs_worker_max_messages
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_sqs_worker_wait_time" {
  name  = "/kishax/${var.environment}/api/sqs_worker_wait_time"
  type  = "String"
  value = var.api_sqs_worker_wait_time
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_sqs_worker_visibility_timeout" {
  name  = "/kishax/${var.environment}/api/sqs_worker_visibility_timeout"
  type  = "String"
  value = var.api_sqs_worker_visibility_timeout
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_shutdown_grace_period" {
  name  = "/kishax/${var.environment}/api/shutdown_grace_period"
  type  = "String"
  value = var.api_shutdown_grace_period
  tags  = var.tags
}

resource "aws_ssm_parameter" "api_log_level" {
  name  = "/kishax/${var.environment}/api/log_level"
  type  = "String"
  value = var.api_log_level
  tags  = var.tags
}

# ===================================
# Terraria Server (i-e) Parameters
# ===================================

resource "aws_ssm_parameter" "terraria_s3_bucket" {
  name  = "/kishax/${var.environment}/terraria/s3_bucket"
  type  = "String"
  value = var.terraria_s3_bucket
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_s3_download_enabled" {
  name  = "/kishax/${var.environment}/terraria/s3_download_enabled"
  type  = "String"
  value = var.terraria_s3_download_enabled
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_server_password" {
  name  = "/kishax/${var.environment}/terraria/server_password"
  type  = "SecureString"
  value = var.terraria_server_password
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_server_port" {
  name  = "/kishax/${var.environment}/terraria/server_port"
  type  = "String"
  value = var.terraria_server_port
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_max_slots" {
  name  = "/kishax/${var.environment}/terraria/max_slots"
  type  = "String"
  value = var.terraria_max_slots
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_server_name" {
  name  = "/kishax/${var.environment}/terraria/server_name"
  type  = "String"
  value = var.terraria_server_name
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_discord_bot_token" {
  name  = "/kishax/${var.environment}/terraria/discord_bot_token"
  type  = "SecureString"
  value = var.terraria_discord_bot_token
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_discord_channel_id" {
  name  = "/kishax/${var.environment}/terraria/discord_channel_id"
  type  = "String"
  value = var.terraria_discord_channel_id
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_rest_api_enabled" {
  name  = "/kishax/${var.environment}/terraria/rest_api_enabled"
  type  = "String"
  value = var.terraria_rest_api_enabled
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_rest_api_port" {
  name  = "/kishax/${var.environment}/terraria/rest_api_port"
  type  = "String"
  value = var.terraria_rest_api_port
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_rest_api_token" {
  name  = "/kishax/${var.environment}/terraria/rest_api_token"
  type  = "SecureString"
  value = var.terraria_rest_api_token
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_rest_api_username" {
  name  = "/kishax/${var.environment}/terraria/rest_api_username"
  type  = "String"
  value = var.terraria_rest_api_username
  tags  = var.tags
}

resource "aws_ssm_parameter" "terraria_rest_api_usergroup" {
  name  = "/kishax/${var.environment}/terraria/rest_api_usergroup"
  type  = "String"
  value = var.terraria_rest_api_usergroup
  tags  = var.tags
}
