# .github/workflows/jira-automation.yml
name: Jira Automation

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

# --- 設定項目 ---
# 新規課題を作成するJiraプロジェクトの情報を設定してください
env:
  JIRA_PROJECT_KEY: SCRUM   # 例: 'PROJ'
  JIRA_ISSUE_TYPE: Task  # 例: 'Task', 'Story'

jobs:
  jira-automation-on-pr:
    name: Jira Automation on Pull Request
    runs-on: ubuntu-latest
    permissions:
      # PRへのコメント投稿とコンテンツの読み取り権限が必要
      contents: read
      pull-requests: write
    steps:
      # -----------------------------------------------------------------
      # 1. Jiraへのログイン
      # -----------------------------------------------------------------
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      # -----------------------------------------------------------------
      # 2. ブランチ名からJira課題キーを抽出
      # -----------------------------------------------------------------
      - name: Find Jira issue key from branch name
        id: find_issue
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.head_ref }}

      # =================================================================
      # 課題キーが見つからなかった場合の処理
      # =================================================================
      - name: Create Jira issue if not found
        if: ${{ !steps.find_issue.outputs.issue }}
        id: create_issue
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ env.JIRA_PROJECT_KEY }}
          issuetype: ${{ env.JIRA_ISSUE_TYPE }}
          summary: ${{ github.event.pull_request.title }}
          description: |
            PRを作成したため、Jira課題を自動作成しました。

            PR Title: ${{ github.event.pull_request.title }}
            PR Body:
            ${{ github.event.pull_request.body }}
            
            PR URL: ${{ github.event.pull_request.html_url }}

      # 【修正】PRへのコメント権限をジョブに追加
      - name: Comment created issue key on PR
        if: ${{ steps.create_issue.outputs.issue }}
        uses: actions/github-script@v7
        with:
          script: |
            const issueKey = "${{ steps.create_issue.outputs.issue }}";
            const jiraBaseUrl = "${{ secrets.JIRA_BASE_URL }}";
            const issueUrl = `${jiraBaseUrl}/browse/${issueKey}`;
            const body = `✅ Jira issue [${issueKey}](${issueUrl}) has been automatically created for this pull request.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });

      # =================================================================
      # 課題キーが見つかった場合の既存の処理
      # =================================================================
      - name: Get Jira Account ID from mapping
        id: get_jira_account_id
        if: steps.find_issue.outputs.issue
        uses: actions/github-script@v7
        env:
          JIRA_USER_MAPPING_JSON: ${{ secrets.JIRA_USER_MAPPING_JSON }}
        with:
          script: |
            const mapping = JSON.parse(process.env.JIRA_USER_MAPPING_JSON || '{}');
            const githubUser = context.actor;
            const jiraAccountId = mapping[githubUser];
            if (!jiraAccountId) {
              core.warning(`No Jira account mapping found for GitHub user: ${githubUser}`);
              return null;
            }
            console.log(`Found Jira Account ID: ${jiraAccountId} for GitHub user: ${githubUser}`);
            return jiraAccountId;
          result-encoding: string

      - name: Assign Jira issue
        if: steps.find_issue.outputs.issue && steps.get_jira_account_id.outputs.result
        uses: atlassian/gajira-cli@v3
        with:
          args: >
            issue assign ${{ steps.find_issue.outputs.issue }} ${{ steps.get_jira_account_id.outputs.result }}

      - name: Get current issue status
        id: get_status
        if: steps.find_issue.outputs.issue
        uses: atlassian/gajira-cli@v3
        with:
          args: >
            issue view ${{ steps.find_issue.outputs.issue }} --json | jq -r '.fields.status.name'

      - name: Transition issue to 'In Review'
        if: >
          steps.find_issue.outputs.issue &&
          (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize') &&
          trim(steps.get_status.outputs.stdout) == '進行中'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.find_issue.outputs.issue }}
          transition: "レビュー待ち"

      - name: Transition issue to 'Done'
        if: >
          steps.find_issue.outputs.issue &&
          github.event.action == 'closed' &&
          github.event.pull_request.merged == true &&
          (trim(steps.get_status.outputs.stdout) == '進行中' || trim(steps.get_status.outputs.stdout) == 'レビュー待ち')
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.find_issue.outputs.issue }}
          transition: "完了"
