name: Update Submodules

on:
  repository_dispatch:
    types: [kishax-web, kishax, gather-bot, discord-bot, test]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Update submodules with unrelated histories
        run: |
          git submodule update --init --remote
          git submodule foreach 'git pull origin main --allow-unrelated-histories'

      - name: Check for changes
        id: git_status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if there are changes
        if: steps.git_status.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: Update submodules to the latest commits"
          git push
