name: Update Submodules

on:
  repository_dispatch:
    types: [kishax-web, kishax, gather-bot, discord-bot, test]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Update submodules to latest commit
        run: |
          git config --global --add safe.directory /github/workspace/apps/discord-bot # ★ discord-botのリポジトリパスに合わせる
          git submodule update --init --remote --merge --rebase

      - name: Check for changes
        id: git_status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit and push if there are changes
        if: steps.git_status.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: Update submodules to the latest commits"
          git push
